#!/usr/bin/env bash

BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VCS_REF=`git rev-parse --short HEAD`

docker build \
  --build-arg BUILD_DATE=$BUILD_DATE \
  --build-arg VCS_REF=$VCS_REF \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME \
  .
